### ISSUE TITLE
How do we add more parameters to the plugin?

### ISSUE THREAD

**Issue by hernandazevedozup** [cotechde/dokka-hugo-plugin#1]
Like the following example:
```

task dokkaHugo(type: org.jetbrains.dokka.gradle.DokkaTask) {

    dependencies {
        dokkaHugoPlugin 'de.cotech:dokka-hugo-plugin:1.1'
    }

    ext {
        capitalizeTitle true
    }
```

**Comment by viniciusguardieirozup** [comment]
We need to remove some parts and capitalize the title and linkTitle on .md files generated by this plugin. Allowing more customization. We can pass a custom configuration saying if we want to capitalize the title, if we want to capitalize the linkTitle, a hashMap to replace some substring of title and a hashMap to replace some substring of the linkTitle.
